name: "Release"

permissions:
  contents: write

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changelog_reader.outputs.changes }}
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v6
      - name: Get version number
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Changelog Reader
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.2.3
        with:
          path: "CHANGELOG.md"
          version: ${{ steps.get_version.outputs.VERSION }}

  windows:
    needs: changelog
    strategy:
      fail-fast: false
      matrix:
        lang: [zh_en]

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Install dependencies
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install frontend dependencies
        run: |
          pnpm config set "build.allow-scripts" all --local
          pnpm install --frozen-lockfile

      - name: Install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      - name: Confirm language
        env:
          MATRIX_LANG: ${{ matrix.lang }}
        run: deno run -A  script/lang.ts

      - name: Build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Built
        env:
          MATRIX_LANG: ${{ matrix.lang }}
          TRAN_VERSION: ${{ needs.changelog.outputs.version }}
          TRAN_PLATFORM: "windows"
        run: deno run -A script/built-windows.ts

      - name: Upload release assets
        id: action_gh_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Tran ${{ needs.changelog.outputs.version }}
          body: |
            ${{ needs.changelog.outputs.changes }}
          files: release/*
          draft: true
          prerelease: false

